### PR TITLE
Add update-gemspec script

### PR DESCRIPTION
**Pull request by aslakhellesoy**
I've added the `update-gemspec` script here, so we don't have to maintain multiple versions across our repositories.

### CODE REVIEW

**Review by aurelien-reeves — APPROVED** [review]

**Comment by jamietanna** [comment]
Would we be happy with replacing this with a Ruby-only version instead? I'd expect that with Ruby it should be easier to modify the files - I'd be happy to look into it

**Comment by aurelien-reeves** [comment]
@jamietanna yeah, good idea! Feel free to submit a PR if you already have some ideas to implement it 👍

**Comment by aslakhellesoy** [comment]
This script has low churn. It's been working well with us for years. What's the problem with the bash script? Why would this be easier to maintain in Ruby?

**Comment by mattwynne** [comment]
I don't know much about Renovate, but is another option to use something like this in our renovate config? https://github.com/reggaemuffin/renovate-gemspec-minimal-example/blob/main/renovate.json

**Comment by aslakhellesoy** [comment]
> I don't know much about Renovate, but is another option to use something like this in our renovate config? https://github.com/reggaemuffin/renovate-gemspec-minimal-example/blob/main/renovate.json

Renovate is not a substitution for a manual upgrade script, because it will only upgrade dependencies if the build passes.

It's a good *complement* though. You could try that config in one of the ruby repos...

**Pull request merged**
